server:
  type: default
  rootPath: ${ROOT_PATH:-/}

db:
  driverClass: ${DB_DRIVER:-org.h2.Driver}
  url: ${DB_URL:-jdbc:h2:mem:yougo;DB_CLOSE_DELAY=-1}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
