name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Maven Cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven

    - name: Unit tests
      run: mvn -B test --file pom.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: yougo-api
        dockerfiles: src/main/docker/Dockerfile.jvm-multi

    - name: Publish to GitHub Packages
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.pkg.github.com/yougo-app/yougo-api/yougo-api
        username: ${{ github.actor }}
        password: ${{ secrets.PUBLISH_TOKEN }}
